{{ $name := .Values.serviceAccountName -}}
{{ $labels := include "ltutil.labels" $ -}}
{{ $namespace := .Values.namespace | default .Release.Namespace -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
{{ $labels | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s_%s" $name $namespace | quote }}
  labels:
{{ $labels | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $name | quote }}
    namespace: {{ $namespace | quote }}
