
rancher:
  project: "c-7xmb9:p-2fqzk"
clusterAdmin: true
serviceAccountName: "postgres-operator-ui"
baseName: "postgres-operator"
team: "acid"

postgres-operator:

  configKubernetes:
    # toggles pod anti affinity on the Postgres pods
    enable_pod_antiaffinity: "true"
    infrastructure_roles_secret_name: postgresql-infrastructure-roles
    spilo_privileged: "true"
    secret_name_template: "{cluster}.credentials.{username}"

  # configure resource requests for the Postgres pods
  configPostgresPodResources:
    # CPU limits for the postgres containers
    default_cpu_limit: "7"
    # cpu request value for the postgres containers
    default_cpu_request: 100m
    # memory limits for the postgres containers
    default_memory_limit: 2Gi
    # memory request value for the postgres containers
    default_memory_request: 100Mi

ui:
  enabled:
  name: "ui"
  longName: "postgres-operator-ui"
  image:
    name: "registry.opensource.zalan.do/acid/postgres-operator-ui"
    tag: "v1.2.0"
    pullPolicy: "IfNotPresent"
  expose:
    http:
      port: 80
      host: "psqlui"
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "300m"
      memory: "3000Mi"
