{{ $namespace := .Release.Namespace -}}
{{ $cephNamespace := .Values.cephNamespace -}}
{{ $serviceAccount := .Values.serviceAccount -}}
{{ $image := .Values.image -}}
{{ $labels := include "ltutil.labels" $ -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ceph-secrets
  namespace: kube-system
  labels:
{{ $labels | indent 4 }}
  annotations:
    helm.sh/hook: {{ .Values.helmHook }}
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- if not (empty $serviceAccount) }}
      serviceAccountName: {{ $serviceAccount }}
      {{- end }}
      containers:

      {{- range $name := .Values.secretsToCopy }}
      - name: copy-secret-{{ $name }}
        image: {{ $image }}
        {{- if empty $serviceAccount }}
        securityContext:
          privileged: true
        {{- end }}
        command: ["/bin/sh"]
        args:
        - -c
        - |
          kubectl -n {{ $cephNamespace }} get secrets {{ $name }} -o json |\
          jq '.metadata.namespace = "{{ $namespace }}"' |\
          jq 'del(.metadata.annotations)' |\
          kubectl create -f -
      {{ end }}
