{{- if .Values.ceph_helm.manifests.deployment_mgr }}
{{- $envAll := . }}
{{- if .Values.ceph_helm.deployment.ceph }}
{{ $labels := tuple $envAll "ceph" "fs-provisioner" | include "helm-toolkit.snippets.kubernetes_metadata_labels" }}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mgr
  labels:
{{ $labels | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: gui
      protocol: TCP
      port: 80
      targetPort: 7000
  selector:
{{ tuple $envAll "ceph" "mgr" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ceph-mgr
  labels:
{{ $labels | indent 4 }}
spec:
  rules:
    - host: mgr.ceph.test.intern
      http:
        paths:
          - backend:
              serviceName: ceph-mgr
              servicePort: gui
{{- end }}
{{- end }}
