{{ if .Values.clusterAdmin -}}
{{ $labels := include "ltutil.labels" . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zalando-postgres-operator-admin
  labels:
{{ $labels | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: zalando-postgres-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
