{{ $cmpDef := .Values.ui -}}
{{ $labels := tuple . $cmpDef.name | include "ltutil.labelall" -}}
{{ $name := $cmpDef.longName }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ $name | quote }}
  labels:
{{ $labels | indent 4 }}
rules:
- apiGroups: ["acid.zalan.do"]
  resources: ["postgresqls"]
  verbs: ["create", "delete", "get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name | quote }}
  labels:
{{ $labels | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name | quote }}
  labels:
{{ $labels | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $name | quote }}
subjects:
- kind: ServiceAccount
  name: {{ $name | quote }}
  namespace: {{ .Release.Namespace }}
