{{ $cmpDef := .Values.ui -}}
{{ $labels := tuple . $cmpDef.name | include "ltutil.labelall" . -}}
{{ $labelsShort := tuple . $cmpDef.name | include "ltutil.labelshortall" . -}}
{{ $name := include "postgres-operator.serviceAccountName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    application: {{ $cmpDef.longName | quote }}
spec:
  type: "ClusterIP"
  selector:
{{ $labelsShort | indent 4 }}
  ports:
    - port: {{ $cmpDef.expose.http.port }}
      protocol: "TCP"
      targetPort: 8081
